### ISSUE TITLE
RaspberryPiOS ARM64 - Version 10.15 installed not current release from flathub

### ISSUE THREAD

**Issue by rekab72** [flathub/org.freefilesync.FreeFileSync#67]
pi@raspberrypi:~ $ flatpak install flathub org.freefilesync.FreeFileSync

Installs Version 10.15 not current release

org.freefilesync.FreeFileSync/aarch64/stable

Any insight to what manual changes need to build to get latest release to install?
I'll work on building locally but if you point me I could contribute to getting flathub install to current version for ARM64/aarch64.

![Screenshot from 2022-01-08 01-54-51](https://user-images.githubusercontent.com/74030695/148635043-b7e5450c-de2d-4a06-a6bd-cbcbfd8d3227.png)

**Comment by kparal** [comment]
FFS is no longer available for `aarch64` on Flathub, because I no longer build it from source (it proved to be extremely complicated and error-prone due to the upstream habit of patching system libraries), and upstream doesn't provide `aarch64` builds. What you got is an extremely old build from the time when it was last built from source. (I reported that problem as https://github.com/flathub/flathub/issues/2755 ).

You need to build FFS from source yourself, get is elsewhere, or start maintaining this Flathub repo, build it from source here and deal with all the pain that arises from it :-)
