### ISSUE TITLE
Offline distributions no longer possible

### ISSUE THREAD

**Issue by Shoegzer** [flathub/org.freefilesync.FreeFileSync#69]
Creation of offline distributions now results in:
```
$ flatpak create-usb . org.freefilesync.FreeFileSync
error: Installed ref ‘app/org.freefilesync.FreeFileSync/x86_64/stable’ is extra-data, and cannot be distributed offline
```
This is a recent issue, as offline distributions could be created with 11.15 (commit b89f9867dfb527f078fba68057aad690d6538d83) but not 11.16 (commit ecb2b0f05852742a0de5831603af9a7975a9ea70).

**Comment by kparal** [comment]
`extra-data` has been introduced in 11.6 (commit 20107b96dc55). So according to the message, anything from 11.6 onwards shouldn't work. There's basically no difference between 11.15 and 11.16, see ecb2b0f0585 . So I don't know how to help you. If 11.15 worked for you, I don't really know why.

But in general, yes, offline flatpak distribution is most probably not possible, because of upstream licensing (see #48).
