### ISSUE TITLE
[Bug] FreeFileSync can't find the command I set up in External Applications

### ISSUE THREAD

**Issue by hyuri** [flathub/org.freefilesync.FreeFileSync#77]
### Issue
Hi, I set up Meld as "Show difference in Meld" ( flatpak run org.gnome.meld "%item_name%" "%item_name2%" ) in External Applications, but when I choose the option in the context menu, I get the error message "/bin/sh: line 1: flatpak run org.gnome.meld: command not found"

![image](https://user-images.githubusercontent.com/18584014/179289296-be712b3a-da82-4629-9111-025b94a4623a.png)

### My System
- Pop!_OS 21.10
- Gnome 40.4
- X11

**Comment by kparal** [comment]
In general, you can only run commands available in the sandbox itself, you can't run anything from the host or from a different sandbox. So if you want to use Meld, you'd have to install FFS in the host natively, not through Flatpak.

But, perhaps there is a way to run a host application through [flatpak-spawn](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn). Try to search the internets to find some examples and discussions about this, and let me know if you figure this out, I'd like to know as well :-) But I'd definitely try this with Meld installed natively on your host, not in yet another flatpak.

A note for future self: Add a remark to FFS flatpak description that you can't (easily) use external applications, because of the sandbox.

**Comment by kparal** [comment]
Another user provided a solution to this problem in #79.
