### ISSUE TITLE
Plan on updating org.freefilesync.FreeFileSync.yml to latest version

### ISSUE THREAD

**Issue by stephankusch** [flathub/org.freefilesync.FreeFileSync#8]
Hi,
since there's still some activity on this repo, do you plan on updating the manifest to build the latest version or if not, what are the issues?
Thanks!

**Comment by kparal** [comment]
Hi, the upstream build system is a mess, and I wasn't able to successfully build a newer version - that was 9.9 (and I think I haven't tried since). There are undeclared dependencies, there are compiler errors, the upstream is difficult to contact, and I'm not really too experienced in building C programs (and very low on spare time). If anyone can build the latest release and submit a PR, I'll happily merge it (see the readme for the current build workflow). I'd also be happy to add that person as a co-maintainer, if he/she is interested in taking care of building latest versions.

**Comment by bgstack15** [comment]
I agree that compiling FreeFileSync is not easy. I'm no C++ developer either. 
If I had to guess, I'd say that upstream uses some rolling-release distro that is ahead of Fedora. I have to roll back the wxWidgets 3.1.1 functions. Here's the dependencies I use on Fedora/EL:
```
# WARNING: the build will FAIL if you have wxGTK3-devel installed. Only wxGTK2-devel should be on the build system.
BuildRequires: boost-devel
BuildRequires: compat-wxGTK3-gtk2-devel
BuildRequires: desktop-file-utils
BuildRequires: gcc-c++
BuildRequires: ImageMagick
BuildRequires: libcurl-devel %{min_libcurl}
BuildRequires: libssh2-devel %{min_libssh2}
BuildRequires: patch
BuildRequires: pkgconfig(gtk+-2.0)
BuildRequires: pkgconfig(libselinux)
BuildRequires: pkgconfig(zlib)
%if 0%{?el6}%{?el7}
BuildRequires: wxGTK-devel
BuildRequires: %{scl_buildreq}
BuildRequires: openssl-%{name}-devel %{min_openssl}
Requires: libcurl %{min_libcurl}
Requires: libssh2 %{min_libssh2}
Requires: openssl-%{name}-libs %{min_openssl}
%else
BuildRequires: openssl-devel
%endif
```
Source: [my gitlab](https://gitlab.com/bgstack15/stackrpms/blob/master/freefilesync/freefilesync.spec)
My patches are in there too and maybe they will help. I've observed that some of our efforts overlap already, specifically the no-updates patch.

**Comment by kparal** [comment]
Another good source of inspiration is Arch's pkgbuild:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freefilesync

Anyone interested in submitting a PR here?
